# Branches that trigger builds on merge to main/release
trigger:
  batch: true
  branches:
    include:
      - main
      - release/*
  paths:
    exclude:
    - README.md
    - docs/*

variables:
  - template: eng/common/templates/variables/pool-providers.yml

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enableRichCodeNavigation: true
      richCodeNavigationLanguage: "csharp"
      enableMicrobuild: true
      enablePublishBuildArtifacts: true
      enablePublishTestResults: true
      enablePublishBuildAssets: true
      enablePublishUsingPipelines: $(_PublishUsingPipelines)
      enableTelemetry: true
      enableSourceBuild: false
      helixRepo: dotnet/interactive-window
      jobs:
      - job: Windows
        pool:
            name: $(DncEngPublicBuildPool)
            demands: ImageOverride -equals windows.vs2022.amd64.open
        variables:
          - name: _OfficialBuildArgs
            value: ''
          - name: _DevDivDropAccessToken
            value: ''
        strategy:
          matrix:
              Debug:
                _BuildConfig: Debug
                _SignType: test
                _DotNetPublishToBlobFeed: false
                _BuildArgs: ''
        steps:
        - checkout: self
          clean: true
          
        - script: eng\common\cibuild.cmd -configuration $(_BuildConfig) -prepareMachine $(_BuildArgs)
          displayName: Build and Test
